name: Call GPT-Codemaster to Create a Pull Request that solves the issue

on:
  issues:
    types: [labeled]

jobs:
  issue_filter:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write
    steps:
    - name: run GPT-codemaster
      uses: kaklik/GPT-Codemaster@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
